---
title: "03_Setup_For_Writing"
author: "Thomas Scherer"
date: "01/11/2017"
output:
  html_notebook:
    toc: yes
    toc_float: yes
  html_document:
    toc: yes
editor_options:
  chunk_output_type: inline
---
<style>
    body .main-container {
        max-width: 100%;
    }
</style>


This setup is for MSSL collaborators who only need to contribute to paper writing and will not need R.

# Workstation Setup

### Dropbox

MSSL uses [Dropbox](https://www.dropbox.com) to share large and proprietary datasets; Dropbox also helps users move between different workstations and keep them synced. If you do not have a Dropbox account, sign up for one at their website. It will automatically download the Dropbox application for you to install. 

Once Dropbox is installed, open the Dropbox folder (likely in your home folder) and create a folder titled "github_private". This folder is where you will keep projects to make edits and then push to the cloud. 

### Github Desktop

[Git](https://git-scm.com/) is a version control system for managing projects. Since you will not be using Git through R, you will be using [Github Desktop](https://desktop.github.com/) to connect with [Github](https://github.com/), the online hosting service for Git repositories. 

If you do not already have a github profile, [sign up for a free account](https://github.com/). When you are logged in, go to [Rex Douglass's account](https://github.com/rexdouglass) and select "Follow" under profile picture. Rex will add you to the repository for a project; you can remind him to by selecting the appropriate repository, selecting the "Issues" tab (between "Code" and "Pull requests") and creating a "New Issue".

Install [Github Desktop](https://desktop.github.com/) by selecting the download for your operating system and running the downloaded installer. When finished, open Github Desktop. On the welcome screen, select "Sign into Github.com" and enter the information for your Github account. Follow the directions through the rest of installation.

### Latex

Section to be added, but if you already have latex on your machine then no other effort should be necessary.



# Project Setup

Once you have setup Dropbox, Github/Github Desktop, and Latex, you are ready to join a project.

Open Github Desktop and select "File -> Clone repository". If you are already part of the project's Github repository you can select it on the **Github.com** tab, otherwise go to the **URL** tab and paste in the url of the project's repository (for example, https://github.com/rexdouglass/InfluenceOfSeapower). In local path, hit **Choose** then find and select the folder "github_private" that you created. Hit **Clone** and the program will grab the repository from the cloud and download it to your computer.

# Workflow

For shared projects, you should follow the following workflow:

### 1. Pull

Before you start working, you should always pull the repository from the cloud so that you have the most recent edition version of everything. Open Github Desktop. In the top left where it says "Current Repository" select the repository you will be working on. Select **Repository -> Pull** to update the files on your computer with the files on the cloud.

### 2. Edit
You can now go into the folder and work as you normally would. To get to the files from Github Desktop, select **Repository -> Show in Exporer**. Most likely, the repository will have a folder named "Paper" that will contain any paper drafts.

### 3. Commit and Push
When you have finished working and saved all of your changes, return to Github Desktop make sure "Current Repository" is the project you were working on. In the left column should be a list of the files that you have made changes to with. The files have boxes to their left, which must be checked to add them to the cloud. At the bottom of that column is a **Summary** box. You must enter something here, preferably a short note of what you worked on. You can now select **Commit to Master**. You have now commited your changes to a local restore point, but you still have to send it to the cloud. Select **Repository -> Push**. 

### Troubleshooting

If someone else made changes to a file that you have changed, Github Desktop will have an error when you try to push your changes. To resolve the issue, you must first pull the changes by selecting **Repository -> Pull**. Once you do, the left column will indicate files that have a conflict between your changes and the other person's changes. 

When you open those files, changes will be indicated with less-than, equal, and greater-than signs like so:

```{r}
<<<<<<< HEAD
Changes you just made
=======
Changes from Cloud
>>>>>>> stringofrandomdigitsandnumbers
```

Make the appropriate changes to resolve the conflicts and save your changes, then return to step 3. to Commit and Push you changes to the cloud. 
